/* tslint:disable */
/* eslint-disable */
//  This file was automatically generated and should not be edited.

export type CreateServiceDBInput = {
  id?: string | null,
  table?: string | null,
  cognitoIdentityID?: string | null,
  userName?: string | null,
  calculatedDataValue?: number | null,
  userActive?: boolean | null,
  billingID?: string | null,
  billingName?: string | null,
  billingActive?: boolean | null,
  billingOwner?: string | null,
  billingPassword?: string | null,
  lambdaName?: string | null,
  functionId?: string | null,
  functionName?: string | null,
  groupName?: string | null,
  groupId?: string | null,
  groupPassword?: string | null,
  groupOwner?: string | null,
  reservationStartTime?: string | null,
  reservationEndTime?: string | null,
  inquiryCategory?: string | null,
  inquiryDetails?: string | null,
};

export type ModelServiceDBConditionInput = {
  table?: ModelStringInput | null,
  cognitoIdentityID?: ModelIDInput | null,
  userName?: ModelStringInput | null,
  calculatedDataValue?: ModelIntInput | null,
  userActive?: ModelBooleanInput | null,
  billingID?: ModelIDInput | null,
  billingName?: ModelStringInput | null,
  billingActive?: ModelBooleanInput | null,
  billingOwner?: ModelStringInput | null,
  billingPassword?: ModelStringInput | null,
  lambdaName?: ModelStringInput | null,
  functionId?: ModelIDInput | null,
  functionName?: ModelStringInput | null,
  groupName?: ModelStringInput | null,
  groupId?: ModelStringInput | null,
  groupPassword?: ModelStringInput | null,
  groupOwner?: ModelStringInput | null,
  reservationStartTime?: ModelStringInput | null,
  reservationEndTime?: ModelStringInput | null,
  inquiryCategory?: ModelStringInput | null,
  inquiryDetails?: ModelStringInput | null,
  and?: Array< ModelServiceDBConditionInput | null > | null,
  or?: Array< ModelServiceDBConditionInput | null > | null,
  not?: ModelServiceDBConditionInput | null,
  createdAt?: ModelStringInput | null,
  updatedAt?: ModelStringInput | null,
  owner?: ModelStringInput | null,
};

export type ModelStringInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export enum ModelAttributeTypes {
  binary = "binary",
  binarySet = "binarySet",
  bool = "bool",
  list = "list",
  map = "map",
  number = "number",
  numberSet = "numberSet",
  string = "string",
  stringSet = "stringSet",
  _null = "_null",
}


export type ModelSizeInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
};

export type ModelIDInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export type ModelIntInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
};

export type ModelBooleanInput = {
  ne?: boolean | null,
  eq?: boolean | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
};

export type ServiceDB = {
  __typename: "ServiceDB",
  id: string,
  table?: string | null,
  cognitoIdentityID?: string | null,
  userName?: string | null,
  calculatedDataValue?: number | null,
  userActive?: boolean | null,
  billingID?: string | null,
  billingName?: string | null,
  billingActive?: boolean | null,
  billingOwner?: string | null,
  billingPassword?: string | null,
  lambdaName?: string | null,
  functionId?: string | null,
  functionName?: string | null,
  groupName?: string | null,
  groupId?: string | null,
  groupPassword?: string | null,
  groupOwner?: string | null,
  reservationStartTime?: string | null,
  reservationEndTime?: string | null,
  inquiryCategory?: string | null,
  inquiryDetails?: string | null,
  createdAt: string,
  updatedAt: string,
  owner?: string | null,
};

export type UpdateServiceDBInput = {
  id: string,
  table?: string | null,
  cognitoIdentityID?: string | null,
  userName?: string | null,
  calculatedDataValue?: number | null,
  userActive?: boolean | null,
  billingID?: string | null,
  billingName?: string | null,
  billingActive?: boolean | null,
  billingOwner?: string | null,
  billingPassword?: string | null,
  lambdaName?: string | null,
  functionId?: string | null,
  functionName?: string | null,
  groupName?: string | null,
  groupId?: string | null,
  groupPassword?: string | null,
  groupOwner?: string | null,
  reservationStartTime?: string | null,
  reservationEndTime?: string | null,
  inquiryCategory?: string | null,
  inquiryDetails?: string | null,
};

export type DeleteServiceDBInput = {
  id: string,
};

export type ModelServiceDBFilterInput = {
  id?: ModelIDInput | null,
  table?: ModelStringInput | null,
  cognitoIdentityID?: ModelIDInput | null,
  userName?: ModelStringInput | null,
  calculatedDataValue?: ModelIntInput | null,
  userActive?: ModelBooleanInput | null,
  billingID?: ModelIDInput | null,
  billingName?: ModelStringInput | null,
  billingActive?: ModelBooleanInput | null,
  billingOwner?: ModelStringInput | null,
  billingPassword?: ModelStringInput | null,
  lambdaName?: ModelStringInput | null,
  functionId?: ModelIDInput | null,
  functionName?: ModelStringInput | null,
  groupName?: ModelStringInput | null,
  groupId?: ModelStringInput | null,
  groupPassword?: ModelStringInput | null,
  groupOwner?: ModelStringInput | null,
  reservationStartTime?: ModelStringInput | null,
  reservationEndTime?: ModelStringInput | null,
  inquiryCategory?: ModelStringInput | null,
  inquiryDetails?: ModelStringInput | null,
  createdAt?: ModelStringInput | null,
  updatedAt?: ModelStringInput | null,
  and?: Array< ModelServiceDBFilterInput | null > | null,
  or?: Array< ModelServiceDBFilterInput | null > | null,
  not?: ModelServiceDBFilterInput | null,
  owner?: ModelStringInput | null,
};

export type ModelServiceDBConnection = {
  __typename: "ModelServiceDBConnection",
  items:  Array<ServiceDB | null >,
  nextToken?: string | null,
};

export enum ModelSortDirection {
  ASC = "ASC",
  DESC = "DESC",
}


export type ModelSubscriptionServiceDBFilterInput = {
  id?: ModelSubscriptionIDInput | null,
  table?: ModelSubscriptionStringInput | null,
  cognitoIdentityID?: ModelSubscriptionIDInput | null,
  userName?: ModelSubscriptionStringInput | null,
  calculatedDataValue?: ModelSubscriptionIntInput | null,
  userActive?: ModelSubscriptionBooleanInput | null,
  billingID?: ModelSubscriptionIDInput | null,
  billingName?: ModelSubscriptionStringInput | null,
  billingActive?: ModelSubscriptionBooleanInput | null,
  billingOwner?: ModelSubscriptionStringInput | null,
  billingPassword?: ModelSubscriptionStringInput | null,
  lambdaName?: ModelSubscriptionStringInput | null,
  functionId?: ModelSubscriptionIDInput | null,
  functionName?: ModelSubscriptionStringInput | null,
  groupName?: ModelSubscriptionStringInput | null,
  groupId?: ModelSubscriptionStringInput | null,
  groupPassword?: ModelSubscriptionStringInput | null,
  groupOwner?: ModelSubscriptionStringInput | null,
  reservationStartTime?: ModelSubscriptionStringInput | null,
  reservationEndTime?: ModelSubscriptionStringInput | null,
  inquiryCategory?: ModelSubscriptionStringInput | null,
  inquiryDetails?: ModelSubscriptionStringInput | null,
  createdAt?: ModelSubscriptionStringInput | null,
  updatedAt?: ModelSubscriptionStringInput | null,
  and?: Array< ModelSubscriptionServiceDBFilterInput | null > | null,
  or?: Array< ModelSubscriptionServiceDBFilterInput | null > | null,
  owner?: ModelStringInput | null,
};

export type ModelSubscriptionIDInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  in?: Array< string | null > | null,
  notIn?: Array< string | null > | null,
};

export type ModelSubscriptionStringInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  in?: Array< string | null > | null,
  notIn?: Array< string | null > | null,
};

export type ModelSubscriptionIntInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
  in?: Array< number | null > | null,
  notIn?: Array< number | null > | null,
};

export type ModelSubscriptionBooleanInput = {
  ne?: boolean | null,
  eq?: boolean | null,
};

export type CreateServiceDBMutationVariables = {
  input: CreateServiceDBInput,
  condition?: ModelServiceDBConditionInput | null,
};

export type CreateServiceDBMutation = {
  createServiceDB?:  {
    __typename: "ServiceDB",
    id: string,
    table?: string | null,
    cognitoIdentityID?: string | null,
    userName?: string | null,
    calculatedDataValue?: number | null,
    userActive?: boolean | null,
    billingID?: string | null,
    billingName?: string | null,
    billingActive?: boolean | null,
    billingOwner?: string | null,
    billingPassword?: string | null,
    lambdaName?: string | null,
    functionId?: string | null,
    functionName?: string | null,
    groupName?: string | null,
    groupId?: string | null,
    groupPassword?: string | null,
    groupOwner?: string | null,
    reservationStartTime?: string | null,
    reservationEndTime?: string | null,
    inquiryCategory?: string | null,
    inquiryDetails?: string | null,
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
  } | null,
};

export type UpdateServiceDBMutationVariables = {
  input: UpdateServiceDBInput,
  condition?: ModelServiceDBConditionInput | null,
};

export type UpdateServiceDBMutation = {
  updateServiceDB?:  {
    __typename: "ServiceDB",
    id: string,
    table?: string | null,
    cognitoIdentityID?: string | null,
    userName?: string | null,
    calculatedDataValue?: number | null,
    userActive?: boolean | null,
    billingID?: string | null,
    billingName?: string | null,
    billingActive?: boolean | null,
    billingOwner?: string | null,
    billingPassword?: string | null,
    lambdaName?: string | null,
    functionId?: string | null,
    functionName?: string | null,
    groupName?: string | null,
    groupId?: string | null,
    groupPassword?: string | null,
    groupOwner?: string | null,
    reservationStartTime?: string | null,
    reservationEndTime?: string | null,
    inquiryCategory?: string | null,
    inquiryDetails?: string | null,
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
  } | null,
};

export type DeleteServiceDBMutationVariables = {
  input: DeleteServiceDBInput,
  condition?: ModelServiceDBConditionInput | null,
};

export type DeleteServiceDBMutation = {
  deleteServiceDB?:  {
    __typename: "ServiceDB",
    id: string,
    table?: string | null,
    cognitoIdentityID?: string | null,
    userName?: string | null,
    calculatedDataValue?: number | null,
    userActive?: boolean | null,
    billingID?: string | null,
    billingName?: string | null,
    billingActive?: boolean | null,
    billingOwner?: string | null,
    billingPassword?: string | null,
    lambdaName?: string | null,
    functionId?: string | null,
    functionName?: string | null,
    groupName?: string | null,
    groupId?: string | null,
    groupPassword?: string | null,
    groupOwner?: string | null,
    reservationStartTime?: string | null,
    reservationEndTime?: string | null,
    inquiryCategory?: string | null,
    inquiryDetails?: string | null,
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
  } | null,
};

export type GetServiceDBQueryVariables = {
  id: string,
};

export type GetServiceDBQuery = {
  getServiceDB?:  {
    __typename: "ServiceDB",
    id: string,
    table?: string | null,
    cognitoIdentityID?: string | null,
    userName?: string | null,
    calculatedDataValue?: number | null,
    userActive?: boolean | null,
    billingID?: string | null,
    billingName?: string | null,
    billingActive?: boolean | null,
    billingOwner?: string | null,
    billingPassword?: string | null,
    lambdaName?: string | null,
    functionId?: string | null,
    functionName?: string | null,
    groupName?: string | null,
    groupId?: string | null,
    groupPassword?: string | null,
    groupOwner?: string | null,
    reservationStartTime?: string | null,
    reservationEndTime?: string | null,
    inquiryCategory?: string | null,
    inquiryDetails?: string | null,
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
  } | null,
};

export type ListServiceDBSQueryVariables = {
  filter?: ModelServiceDBFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListServiceDBSQuery = {
  listServiceDBS?:  {
    __typename: "ModelServiceDBConnection",
    items:  Array< {
      __typename: "ServiceDB",
      id: string,
      table?: string | null,
      cognitoIdentityID?: string | null,
      userName?: string | null,
      calculatedDataValue?: number | null,
      userActive?: boolean | null,
      billingID?: string | null,
      billingName?: string | null,
      billingActive?: boolean | null,
      billingOwner?: string | null,
      billingPassword?: string | null,
      lambdaName?: string | null,
      functionId?: string | null,
      functionName?: string | null,
      groupName?: string | null,
      groupId?: string | null,
      groupPassword?: string | null,
      groupOwner?: string | null,
      reservationStartTime?: string | null,
      reservationEndTime?: string | null,
      inquiryCategory?: string | null,
      inquiryDetails?: string | null,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
    } | null >,
    nextToken?: string | null,
  } | null,
};

export type ServiceDBSByTableQueryVariables = {
  table: string,
  sortDirection?: ModelSortDirection | null,
  filter?: ModelServiceDBFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ServiceDBSByTableQuery = {
  serviceDBSByTable?:  {
    __typename: "ModelServiceDBConnection",
    items:  Array< {
      __typename: "ServiceDB",
      id: string,
      table?: string | null,
      cognitoIdentityID?: string | null,
      userName?: string | null,
      calculatedDataValue?: number | null,
      userActive?: boolean | null,
      billingID?: string | null,
      billingName?: string | null,
      billingActive?: boolean | null,
      billingOwner?: string | null,
      billingPassword?: string | null,
      lambdaName?: string | null,
      functionId?: string | null,
      functionName?: string | null,
      groupName?: string | null,
      groupId?: string | null,
      groupPassword?: string | null,
      groupOwner?: string | null,
      reservationStartTime?: string | null,
      reservationEndTime?: string | null,
      inquiryCategory?: string | null,
      inquiryDetails?: string | null,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
    } | null >,
    nextToken?: string | null,
  } | null,
};

export type ServiceDBSByCognitoIdentityIDQueryVariables = {
  cognitoIdentityID: string,
  sortDirection?: ModelSortDirection | null,
  filter?: ModelServiceDBFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ServiceDBSByCognitoIdentityIDQuery = {
  serviceDBSByCognitoIdentityID?:  {
    __typename: "ModelServiceDBConnection",
    items:  Array< {
      __typename: "ServiceDB",
      id: string,
      table?: string | null,
      cognitoIdentityID?: string | null,
      userName?: string | null,
      calculatedDataValue?: number | null,
      userActive?: boolean | null,
      billingID?: string | null,
      billingName?: string | null,
      billingActive?: boolean | null,
      billingOwner?: string | null,
      billingPassword?: string | null,
      lambdaName?: string | null,
      functionId?: string | null,
      functionName?: string | null,
      groupName?: string | null,
      groupId?: string | null,
      groupPassword?: string | null,
      groupOwner?: string | null,
      reservationStartTime?: string | null,
      reservationEndTime?: string | null,
      inquiryCategory?: string | null,
      inquiryDetails?: string | null,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
    } | null >,
    nextToken?: string | null,
  } | null,
};

export type ServiceDBSByBillingIDQueryVariables = {
  billingID: string,
  sortDirection?: ModelSortDirection | null,
  filter?: ModelServiceDBFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ServiceDBSByBillingIDQuery = {
  serviceDBSByBillingID?:  {
    __typename: "ModelServiceDBConnection",
    items:  Array< {
      __typename: "ServiceDB",
      id: string,
      table?: string | null,
      cognitoIdentityID?: string | null,
      userName?: string | null,
      calculatedDataValue?: number | null,
      userActive?: boolean | null,
      billingID?: string | null,
      billingName?: string | null,
      billingActive?: boolean | null,
      billingOwner?: string | null,
      billingPassword?: string | null,
      lambdaName?: string | null,
      functionId?: string | null,
      functionName?: string | null,
      groupName?: string | null,
      groupId?: string | null,
      groupPassword?: string | null,
      groupOwner?: string | null,
      reservationStartTime?: string | null,
      reservationEndTime?: string | null,
      inquiryCategory?: string | null,
      inquiryDetails?: string | null,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
    } | null >,
    nextToken?: string | null,
  } | null,
};

export type ServiceDBSByGroupIdQueryVariables = {
  groupId: string,
  sortDirection?: ModelSortDirection | null,
  filter?: ModelServiceDBFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ServiceDBSByGroupIdQuery = {
  serviceDBSByGroupId?:  {
    __typename: "ModelServiceDBConnection",
    items:  Array< {
      __typename: "ServiceDB",
      id: string,
      table?: string | null,
      cognitoIdentityID?: string | null,
      userName?: string | null,
      calculatedDataValue?: number | null,
      userActive?: boolean | null,
      billingID?: string | null,
      billingName?: string | null,
      billingActive?: boolean | null,
      billingOwner?: string | null,
      billingPassword?: string | null,
      lambdaName?: string | null,
      functionId?: string | null,
      functionName?: string | null,
      groupName?: string | null,
      groupId?: string | null,
      groupPassword?: string | null,
      groupOwner?: string | null,
      reservationStartTime?: string | null,
      reservationEndTime?: string | null,
      inquiryCategory?: string | null,
      inquiryDetails?: string | null,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
    } | null >,
    nextToken?: string | null,
  } | null,
};

export type OnCreateServiceDBSubscriptionVariables = {
  filter?: ModelSubscriptionServiceDBFilterInput | null,
  owner?: string | null,
};

export type OnCreateServiceDBSubscription = {
  onCreateServiceDB?:  {
    __typename: "ServiceDB",
    id: string,
    table?: string | null,
    cognitoIdentityID?: string | null,
    userName?: string | null,
    calculatedDataValue?: number | null,
    userActive?: boolean | null,
    billingID?: string | null,
    billingName?: string | null,
    billingActive?: boolean | null,
    billingOwner?: string | null,
    billingPassword?: string | null,
    lambdaName?: string | null,
    functionId?: string | null,
    functionName?: string | null,
    groupName?: string | null,
    groupId?: string | null,
    groupPassword?: string | null,
    groupOwner?: string | null,
    reservationStartTime?: string | null,
    reservationEndTime?: string | null,
    inquiryCategory?: string | null,
    inquiryDetails?: string | null,
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
  } | null,
};

export type OnUpdateServiceDBSubscriptionVariables = {
  filter?: ModelSubscriptionServiceDBFilterInput | null,
  owner?: string | null,
};

export type OnUpdateServiceDBSubscription = {
  onUpdateServiceDB?:  {
    __typename: "ServiceDB",
    id: string,
    table?: string | null,
    cognitoIdentityID?: string | null,
    userName?: string | null,
    calculatedDataValue?: number | null,
    userActive?: boolean | null,
    billingID?: string | null,
    billingName?: string | null,
    billingActive?: boolean | null,
    billingOwner?: string | null,
    billingPassword?: string | null,
    lambdaName?: string | null,
    functionId?: string | null,
    functionName?: string | null,
    groupName?: string | null,
    groupId?: string | null,
    groupPassword?: string | null,
    groupOwner?: string | null,
    reservationStartTime?: string | null,
    reservationEndTime?: string | null,
    inquiryCategory?: string | null,
    inquiryDetails?: string | null,
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
  } | null,
};

export type OnDeleteServiceDBSubscriptionVariables = {
  filter?: ModelSubscriptionServiceDBFilterInput | null,
  owner?: string | null,
};

export type OnDeleteServiceDBSubscription = {
  onDeleteServiceDB?:  {
    __typename: "ServiceDB",
    id: string,
    table?: string | null,
    cognitoIdentityID?: string | null,
    userName?: string | null,
    calculatedDataValue?: number | null,
    userActive?: boolean | null,
    billingID?: string | null,
    billingName?: string | null,
    billingActive?: boolean | null,
    billingOwner?: string | null,
    billingPassword?: string | null,
    lambdaName?: string | null,
    functionId?: string | null,
    functionName?: string | null,
    groupName?: string | null,
    groupId?: string | null,
    groupPassword?: string | null,
    groupOwner?: string | null,
    reservationStartTime?: string | null,
    reservationEndTime?: string | null,
    inquiryCategory?: string | null,
    inquiryDetails?: string | null,
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
  } | null,
};
